### PR TITLE
Added support for Variable Attributes

### PR DESCRIPTION
**Pull request by shubhamnarlawar77**
@marxin : review request || @andikleen : review request

### CODE REVIEW

**Comment by marxin** [comment]
Looks good to me.

**Comment by shubhamnarlawar77** [comment]
Should I merge it?

**Comment by marxin** [comment]
> Should I merge it?

Yes please.

**Comment by andikleen** [comment]
On Tue, Aug 13, 2019 at 07:00:27AM -0700, Shubham Narlawar wrote:
> @marxin : review request || @andikleen : review request
> 
> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/shubhamnarlawar77/csmith/pull/26

Looks good to me too.

-Andi

**Comment by shubhamnarlawar77** [comment]
Thank you. It has been merged. Can you give review on Vector Extension pull request @andikleen ?

**Pull request merged**
