### PR TITLE
Added support for Vector Extensions

### PR DESCRIPTION
**Pull request by shubhamnarlawar77**

### CODE REVIEW

**Comment by shubhamnarlawar77** [comment]
@marxin : review request && @andikleen : review request

**Comment by shubhamnarlawar77** [comment]
Here, I have converted 1D array to vector variables.

Note - Below error is occurred due to addition of above patch
`error: initializer element is not computable at load time`. It is due to other variables are assigned random location of vector i.e. contains constants. (which is not correct I guess)

I have sent this patch to verify Is it appropriate way? Also, I am going to fix above error.

**Comment by andikleen** [comment]
There are a lot more vector types than just v4si. I think you need a table, and then randomly select one.

**Comment by andikleen** [comment]
Also the actual table will depend on the target, e.g. different for SSE vs AVX vs AVX512. Might need some options to select that.

**Comment by shubhamnarlawar77** [comment]
> There are a lot more vector types than just v4si. I think you need a table, and then randomly select one.

Sure. Are these below types you are referring rather than v4si? (from GCC doc)
`float - v4sf`
`double - v4df`
`unsigned long long - v4di`

**Comment by andikleen** [comment]
On Mon, Jul 15, 2019 at 10:23:39AM -0700, Shubham Narlawar wrote:
>     There are a lot more vector types than just v4si. I think you need a table,
>     and then randomly select one.
> 
> Sure. Are these below types you are referring rather than v4si? (from GCC doc)
> typedef int v4si __attribute__ ((vector_size (16))); typedef float v4sf
> __attribute__ ((vector_size (16))); typedef double v4df __attribute__
> ((vector_size (32))); typedef unsigned long long v4di __attribute__
> ((vector_size (32)));

At least AVX has more:

typedef double __v4df __attribute__ ((__vector_size__ (32)));
typedef float __v8sf __attribute__ ((__vector_size__ (32)));
typedef long long __v4di __attribute__ ((__vector_size__ (32)));
typedef unsigned long long __v4du __attribute__ ((__vector_size__
(32)));
typedef int __v8si __attribute__ ((__vector_size__ (32)));
typedef unsigned int __v8su __attribute__ ((__vector_size__ (32)));
typedef short __v16hi __attribute__ ((__vector_size__ (32)));
typedef unsigned short __v16hu __attribute__ ((__vector_size__ (32)));
typedef char __v32qi __attribute__ ((__vector_size__ (32)));
typedef unsigned char __v32qu __attribute__ ((__vector_size__ (32)))

AVX 512:

ypedef short __v32hi __attribute__ ((__vector_size__ (64)));
typedef char __v64qi __attribute__ ((__vector_size__ (64)));
typedef long long __v8di __attribute__ ((__vector_size__ (64)));
typedef int __v16si __attribute__ ((__vector_size__ (64)));
typedef long long __m512i __attribute__ ((__vector_size__ (64),
__may_alias__));
typedef double __m512d __attribute__ ((__vector_size__ (64),
__may_alias__));
typedef double __v8df __attribute__ ((__vector_size__ (64)));
typedef float __v16sf __attribute__ ((__vector_size__ (64)));
typedef float __m512 __attribute__ ((__vector_size__ (64),
__may_alias__));
typedef double __m512d __attribute__ ((__vector_size__ (64),
__may_alias__));
typedef double __v8df __attribute__ ((__vector_size__ (64)));
typedef float __v16sf __attribute__ ((__vector_size__ (64)));
typedef long long __v8di __attribute__ ((__vector_size__ (64)));
typedef unsigned long long __v8du __attribute__ ((__vector_size__
(64)));
typedef int __v16si __attribute__ ((__vector_size__ (64)));
typedef unsigned int __v16su __attribute__ ((__vector_size__ (64)));
typedef short __v32hi __attribute__ ((__vector_size__ (64)));
typedef unsigned short __v32hu __attribute__ ((__vector_size__ (64)));
typedef char __v64qi __attribute__ ((__vector_size__ (64)));
typedef unsigned char __v64qu __attribute__ ((__vector_size__ (64)));
typedef float __m512 __attribute__ ((__vector_size__ (64),
__may_alias__));
typedef long long __m512i __attribute__ ((__vector_size__ (64),
__may_alias__));
typedef double __m512d __attribute__ ((__vector_size__ (64),
__may_alias__));
typedef float __m512_u __attribute__ ((__vector_size__ (64),
__may_alias__, __aligned__ (1)));
typedef long long __m512i_u __attribute__ ((__vector_size__ (64),
__may_alias__, __aligned__ (1)));
typedef double __m512d_u __attribute__ ((__vector_size__ (64),
__may_alias__, __aligned__ (1)));
typedef long long __v8di __attribute__ ((__vector_size__ (64)));
typedef int __v16si __attribute__ ((__vector_size__ (64)));
typedef long long __m512i __attribute__ ((__vector_size__ (64),
__may_alias__));



For some of them to run it on your system (if you don't have AVX or
AVX-512) you may need SDE
(https://software.intel.com/en-us/articles/intel-software-development-emulator)

Or find some system in the gcc compile pool that have.

Also it may not work to mix the types. So when generating expressions
with multiple variables you may need to make sure they all have the same
type.

**Comment by shubhamnarlawar77** [comment]
Taking a step backward as converting 1D array variables to vector variables seems inappropriate.

1. After trying several approaches, I have decided to come up with a new class `VectorVariable` (derived from base class `Variable`) which will generate vector variables from new `vector types` defined in `Type` class.
2. For storing types, I have used separate `enum` for vector (Csmith uses enum to store all the types).
3. Here, I am able to generate vector types in the program but next step is to complete these vector variable definations.
e.g. At present, 
              `typedef int v4si __attribute__(vector_size(32));`
              `v4si a = {7};`
              Now, when assigning to it a different value, we use `a[0] = 10`.
     But in Csmith, it is generating `a = 10` which throws error due to incompatibility.

Hence, `Vector Variable` are to be treated in special way as `array variables`. (Hence, I have created a derived class from base Variable class).

Am I heading in correct path?

**Comment by marxin** [comment]
> Am I heading in correct path?

I guess a question for @andikleen ?

**Comment by shubhamnarlawar77** [comment]
> > Am I heading in correct path?
> 
> I guess a question for @andikleen ?

Yes!

**Comment by andikleen** [comment]
Approach sounds reasonable to me.

Yes the assignment needs to be special cased to generator vectors too.

**Comment by shubhamnarlawar77** [comment]
Yes. 
Is this approach fine?

**Comment by andikleen** [comment]
Yes should be good

**Pull request closed without merging**
