### PR TITLE
Added support for Common Type Attributes

### PR DESCRIPTION
**Pull request by shubhamnarlawar77**

### CODE REVIEW

**Comment by shubhamnarlawar77** [comment]
'@marxin : review request'

**Comment by shubhamnarlawar77** [comment]
At first, attributes instances for struct and union type are created and the rest infrastructure is same as creating Function Attributes.

Note -

1. Sometimes, I get a warning - union can not be made transparent
2. common and uncommon are applicable to variable attributes and not type attributes. By mistakely, I classified them in type attributes section.
3. Bool variables are required to identify struct and union from normal variables, hence these are set during generation phase which can be used later in output phase.

**Comment by marxin** [comment]
> At first, attributes instances for struct and union type are created and the rest infrastructure is same as creating Function Attributes.

I don't like the approach, I would prefer to generalize `FunctionAttribute` and reuse it for functions, types and variables. I would probably recommend to rebase the `csmith-gcc-v2` where you will create the generalization and then make pull request that will contain all the commits we have so far. Then another commits for variables and types can be added.

**Comment by shubhamnarlawar77** [comment]
> > At first, attributes instances for struct and union type are created and the rest infrastructure is same as creating Function Attributes.
> 
> I don't like the approach, I would prefer to generalize `FunctionAttribute` and reuse it for functions, types and variables. I would probably recommend to rebase the `csmith-gcc-v2` where you will create the generalization and then make pull request that will contain all the commits we have so far. Then another commits for variables and types can be added.

Sure. It is appropriate approach.
 
To print attributes in a list format, I have 2 appproach - 
1. Print each attribute using `__attribute__(())` using current architecture which will be then used for type and variable attributes.
2. Print attributes in list. For this, I need to remove probability from the infrastructure. Instead, I can check rnd_flipcoin(prob) and then pass to infrastructure. Similarly, I can apply to type and variable attributes. In this way, I can print attributes in a list.

Which approach do you suggest?

**Comment by marxin** [comment]
I don't understand that, please provide an example what you mean.

**Comment by shubhamnarlawar77** [comment]
> I don't understand that, please provide an example what you mean.

I was asking which one of below you want as output -
for example -  
1. `__attribute__((used))` `__attribute__((unused))`
Generalizing this way requires no change in base class.

2. `__attribute__((used, unused))`
To generalize in this way, I need to remove prob from base class
`class FunctionAttribute{
public:
       string name;
       int prob;
       OutputAttributes();
};`
Instead I need to check probability before passing to `OutputAttributes()` so that I can print list of attributes as above.

**Comment by marxin** [comment]
> 2\. `__attribute__((used, unused))`
>     To generalize in this way, I need to remove prob from base class
>     `class FunctionAttribute{ public: string name; int prob; OutputAttributes(); };`
>     Instead I need to check probability before passing to `OutputAttributes()` so that I can print list of attributes as above.

I prefer this one. Why do you need to remove that?

**Comment by shubhamnarlawar77** [comment]
> > 2. `__attribute__((used, unused))`
> > To generalize in this way, I need to remove prob from base class
> > `class FunctionAttribute{ public: string name; int prob; OutputAttributes(); };`
> > Instead I need to check probability before passing to `OutputAttributes()` so that I can print list of attributes as above.
> 
> I prefer this one. Why do you need to remove that?

In output phase, if some of attributes do not pass probabilities in `OutputAttributes()` then I get output like `__attribute__((used, unused, , , hot, cold, , aligned(16)))`
This is due to I need to take care of other class like `Type class` which will generate attributes from classes defined in `Function class`.

**Comment by marxin** [comment]
> In output phase, if some of attributes do not pass probabilities in `OutputAttributes()` then I get output like `__attribute__((used, unused, , , hot, cold, , aligned(16)))`
> This is due to I need to take care of other class like `Type class` which will generate attributes from classes defined in `Function class`.

I'm sorry but I really don't see why is that problem. The comma is only printed in `FunctionAttribute::OutputAttribute` and you should be able to deal with the problem here.

**Comment by shubhamnarlawar77** [comment]
> > In output phase, if some of attributes do not pass probabilities in `OutputAttributes()` then I get output like `__attribute__((used, unused, , , hot, cold, , aligned(16)))`
> > This is due to I need to take care of other class like `Type class` which will generate attributes from classes defined in `Function class`.
> 
> I'm sorry but I really don't see why is that problem. The comma is only printed in `FunctionAttribute::OutputAttribute` and you should be able to deal with the problem here.

There is no problem for generating function attributes. But when I use output for type attributes, it mess the output.

**Comment by marxin** [comment]
So that you will have to show me a patch (commit) that will present the limitation. This discussion is too much abstract without a real code.

**Comment by shubhamnarlawar77** [comment]
> So that you will have to show me a patch (commit) that will present the limitation. This discussion is too much abstract without a real code.

Sure. I will rebase it to `Common Function Attribute` and will push a patch.

**Pull request closed without merging**
