### PR TITLE
Removed old patch of Aligned FunctionAttribute

### PR DESCRIPTION
**Pull request by shubhamnarlawar77**

### CODE REVIEW

**Comment by shubhamnarlawar77** [comment]
'@marxin : review request'

I forgot to remove old patch of aligned function attribute while doing rebase. Should I merge into base branch?

**Comment by marxin** [comment]
I would like to create `csmith-gcc-v2` which you'll base on current master and which will contain the new commits. I prefer to use `git rebase origin/master` then using `git merge origin/master`.

**Comment by shubhamnarlawar77** [comment]
> I would like to create `csmith-gcc-v2` which you'll base on current master and which will contain the new commits. I prefer to use `git rebase origin/master` then using `git merge origin/master`.

Do you mean creating master clone as csmith-gcc-v2 and then merging commits that have been done?

Note - My master branch contains an unmerged patch of `computed goto/ labels as values` which I have sent request to csmith

**Comment by marxin** [comment]
> Do you mean creating master clone as csmith-gcc-v2 and then merging commits that have been done?

Not merging, but using `git am` for patches created with `git format-patch`.

> Do you mean creating master clone as csmith-gcc-v2 and then merging commits that have been done?

Not merging, but using `git am` for patches created with `git format-patch`.

> 
> Note - My master branch contains an unmerged patch of `computed goto/ labels as values` which I have sent request to csmith

Then exclude the patch and keep it in the old branch.

**Comment by marxin** [comment]
Or you can you `git cherry-pick`.

**Comment by shubhamnarlawar77** [comment]
> Or you can you `git cherry-pick`.

Got it.

**Comment by shubhamnarlawar77** [comment]
> I would like to create `csmith-gcc-v2` which you'll base on current master and which will contain the new commits. I prefer to use `git rebase origin/master` then using `git merge origin/master`.

Done. I have created a branch `csmith-gcc-v2` from my master branch.
1. Removed `computed-goto` from it and synchronized it with original `csmith-master`.
2. Added `always_inline`
3. Added `common function attributes`
4. Added `aligned` function attribute
5. Added `section` function attribute

Hence, we got series of patches in the base branch `csmith-gcc-v2`

**Comment by marxin** [comment]
Great, thank you for it. It will pay back as we'll eventually make a pull request of all the commits that are in the branch.

**Comment by shubhamnarlawar77** [comment]
> Great, thank you for it. It will pay back as we'll eventually make a pull request of all the commits that are in the branch.

Sure. Should I delete this branch `csmith-gcc-remove-old-aligned`?

**Comment by shubhamnarlawar77** [comment]
The base branch will be `csmith-gcc-v2`. For reviewing pull request, I will make branch of base branch. Same process will be followed as earlier. Is this fine?

**Comment by marxin** [comment]
> Sure. Should I delete this branch `csmith-gcc-remove-old-aligned`?

Let's keep it.

**Comment by shubhamnarlawar77** [comment]
> > Sure. Should I delete this branch `csmith-gcc-remove-old-aligned`?
> 
> Let's keep it.

Sure. Keeping it is not a problem.

**Pull request closed without merging**
