### PR TITLE
Added support for Alias Function Attribute

### PR DESCRIPTION
**Pull request by shubhamnarlawar77**

### CODE REVIEW

**Comment by shubhamnarlawar77** [comment]
'@marxin : review request'

**Comment by shubhamnarlawar77** [comment]
I have declared `alias` declaration of functions. Those function calls which pass `rnd_flipcoin()`, will be called through `alias`.

**Comment by marxin** [comment]
The patch is fine, please apply it.

**Comment by shubhamnarlawar77** [comment]
> The patch is fine, please apply it.

Sure.

**Comment by marxin** [comment]
Every time you merge into `csmith-gcc-v2` please rebase the branch so that you remove the merge commit. Thanks.

**Comment by shubhamnarlawar77** [comment]
> Every time you merge into `csmith-gcc-v2` please rebase the branch so that you remove the merge commit. Thanks.

Got it. Done

**Pull request merged**
